### ISSUE TITLE
fix client handling of proxy disconnect

### ISSUE THREAD

**Issue by AhmedAlK** [mehrdadjg/Scalability-Dolphins#15]
When the proxy disconnects, the client enters a loop where EOFException is repeatedly thrown.

Testing sequence:
1. Launch proxy
2. launch client connected to proxy
3. transmit any character to the proxy from the client
4. disconnect the proxy
5. observe client console output

> ERROR IN CLIENT. Cannot read from the incoming stream.
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:154)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:223)
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:337)
	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at network.ClientReceiver.run(ClientReceiver.java:33)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mehrdadjg** [comment]
Hi,

It's because the code is running on the _debugging_ mode. if we turn that
off it's going to be okay.
